export const CARD_DATABASE = [
  {
    id: 'pika-rapido',
    name: 'Pika-Rápido',
    basePokemonReference: 'Pikachu',
    costElixir: 3,
    hp: 430,
    damage: 92,
    attackSpeed: 0.72,
    speed: 78,
    range: 30,
    targetType: 'ground',
    isAoE: false,
    color: '#f5d34d',
    sprite: 'https://play.pokemonshowdown.com/sprites/ani/pikachu.gif',
    staticIcon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png',
    role: 'Asalto veloz'
  },
  {
    id: 'snor-tanque',
    name: 'Snor-Tanque',
    basePokemonReference: 'Snorlax',
    costElixir: 5,
    hp: 2100,
    damage: 185,
    attackSpeed: 1.6,
    speed: 24,
    range: 36,
    targetType: 'buildings_only',
    isAoE: false,
    color: '#82c6cb',
    sprite: 'https://play.pokemonshowdown.com/sprites/ani/snorlax.gif',
    staticIcon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/143.png',
    role: 'Tanque puro'
  },
  {
    id: 'char-ignis',
    name: 'Char-Ignis',
    basePokemonReference: 'Charizard',
    costElixir: 4,
    hp: 750,
    damage: 105,
    attackSpeed: 1.15,
    speed: 46,
    range: 130,
    targetType: 'ground',
    canTargetAir: true,
    isFlying: true,
    isAoE: true,
    splashRadius: 52,
    color: '#fa9154',
    sprite: 'https://play.pokemonshowdown.com/sprites/ani/charizard.gif',
    staticIcon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/6.png',
    role: 'Volador / Salpicadura'
  },
  {
    id: 'scizor-guerrero',
    name: 'Scizor-Guerrero',
    basePokemonReference: 'Scizor',
    costElixir: 4,
    hp: 1050,
    damage: 128,
    attackSpeed: 1.05,
    speed: 42,
    range: 36,
    targetType: 'ground',
    isAoE: true,
    splashRadius: 55,
    color: '#e95d57',
    sprite: 'https://play.pokemonshowdown.com/sprites/ani/scizor.gif',
    staticIcon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/212.png',
    role: 'Mini-tanque / Área'
  },
  {
    id: 'gengar-horda',
    name: 'Gengar-Horda',
    basePokemonReference: 'Gastly',
    costElixir: 3,
    hp: 65,
    damage: 42,
    attackSpeed: 0.8,
    speed: 68,
    range: 24,
    targetType: 'ground',
    isAoE: false,
    count: 8,
    color: '#bb8be8',
    sprite: 'https://play.pokemonshowdown.com/sprites/ani/gastly.gif',
    staticIcon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/92.png',
    role: 'Horda (8 espectros)'
  },
  {
    id: 'decidue-tirador',
    name: 'Decidue-Tirador',
    basePokemonReference: 'Decidueye',
    costElixir: 4,
    hp: 490,
    damage: 118,
    attackSpeed: 1.15,
    speed: 36,
    range: 165,
    targetType: 'ground',
    canTargetAir: true,
    isAoE: false,
    color: '#abd36c',
    sprite: 'https://play.pokemonshowdown.com/sprites/ani/decidueye.gif',
    staticIcon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/724.png',
    role: 'Tirador de precisión'
  },
  {
    id: 'volt-defensa',
    name: 'Volt-Torre',
    basePokemonReference: 'Magnemite',
    costElixir: 4,
    hp: 820,
    damage: 75,
    attackSpeed: 0.85,
    speed: 0,
    range: 148,
    targetType: 'ground',
    canTargetAir: true,
    isAoE: false,
    isBuilding: true,
    lifetime: 35,
    color: '#75d5dd',
    sprite: 'https://play.pokemonshowdown.com/sprites/ani/magnemite.gif',
    staticIcon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/81.png',
    role: 'Defensa eléctrica'
  },
  {
    id: 'bola-ignea',
    name: 'Llamarada',
    basePokemonReference: 'Arcanine',
    costElixir: 4,
    hp: 1,
    damage: 380,
    attackSpeed: 0,
    speed: 0,
    range: 0,
    targetType: 'ground',
    canTargetAir: true,
    isAoE: true,
    radius: 72,
    towerDamageFactor: 0.38,
    color: '#ff6238',
    sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/fire-stone.png',
    staticIcon: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/items/fire-stone.png',
    role: 'Hechizo de área'
  }
];
